[build]
  functions = "functions"
  command = "npm run build:netlify"
  publish = "dist"

[dev]
  publish = "dist"


[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "script-src 'self'"
    Referrer-Policy = "same-origin"
    Permissions-Policy = "fullscreen=(), geolocation=()"
    X-Content-Type-Options = "'nosniff' always"

    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''